In [125]:
import numpy as np
def cos_sim(vec1, vec2):
    dot = np.dot(vec1, vec2)
    norm1 = np.linalg.norm(vec1)
    norm2 = np.linalg.norm(vec2)
    try:
        sim = dot / (norm1 * norm2)
    except:
        sim = 0
    return sim

cos_sim([1,1], [0, 1])


0.7071067811865475

In [83]:
import json
import csv
import pandas as pd
# !wc ./course_list.csv

def course_list():
    course = []
    with open('course_list.csv') as f:
        for line in f:
            # line = f.readline()
            # print(line)
            line = line.replace('\n', '')
            course.append(line)
        return course

courses = course_list()
courses
#len(courses)

['生産システムI',
 '特別講義 国際紛争研究(外国語科目)',
 "特別講義 Japan in Today's World(外国語科目)",
 '生態統計学',
 '商法演習',
 'ロシア・旧ソ連法',
 '技術倫理',
 '健康心理学',
 '機械設計及び製図',
 '農作業実習',
 'グローバル生命倫理',
 '国法学',
 '国際政治史',
 '特別講義 Conflict Prevention and Post-Conflict Politics(外国語科目) ',
 '道徳と教育',
 '臨床現象学',
 '教育の公共性を考える',
 '専門講義',
 '価値と教育III',
 '日本政治思想史',
 '地域経済フィールドワーク実習',
 '医薬品・医療ビジネス',
 '英語科教育法III',
 '教育の方法',
 '高度教養特殊演習(こころの総合人間科学演習)',
 '教育課程',
 '教育と社会',
 '高度教養特殊演習(ダイバーシティ社会をつくる技術)',
 '総合日本語 I(2)(L2)',
 '高度教養特殊演習(ひとをつなぐ まちをつくる)',
 '総合日本語 I(1)(L1)',
 '東西文明学II(言語と歴史3)',
 '東西文明学II(言語と歴史1)',
 '複合系計画論',
 '超域文化科学高度教養(芸術作品分析法)',
 '中国語学中国文学演習IX',
 'スポーツ科学概論',
 'プログラミング基礎',
 '認知脳科学概論',
 '広域システム概論I',
 '学際科学概論',
 '地理・空間基礎論II',
 '地理・空間基礎論I',
 '東西文明学III(国際社会科学2) ',
 '科学技術社会論',
 '数理科学概論 ',
 '進化理論[高度教養科目] ',
 '物質科学概論',
 '広域システム概論II ',
 '生命科学概論 ',
 'エネルギー科学概論 ',
 '東西文明学I(思想と批評1) ',
 '情報科教育法II ',
 '情報科教育法I',
 '英語科教育法I',
 '科学技術史概論',
 '理科教育法II',
 '理科教育法I',
 '数学科教育法I',
 '公民科教育法I',
 '英語科教育法II',
 '東西文明学I(環境と身体5) ',
 '東西文明学I(環境と身体1) ',
 '東西文明学I(環境と身

In [84]:
def vocab_list():
    course = []
    with open('keyword_list.csv') as f:
        for line in f:
            # line = f.readline()
            # print(line)
            line = line.replace('\n', '')
            course.append(line)
        return course

vocab = vocab_list()
vocab

['演習',
 '特殊',
 '講義',
 '科学',
 '研究',
 '工学',
 '社会',
 'コース',
 '日本',
 '文化',
 '文学',
 '理学',
 '化学',
 '語学',
 '実習',
 '生物',
 '共通',
 '基礎',
 '情報',
 '特別',
 '英語',
 '環境',
 'シス',
 'システム',
 '国語',
 '国際',
 '専門',
 '数理',
 '経済',
 '概論',
 '実験',
 '言語',
 '力学',
 '教育',
 '日本語',
 '物理',
 '史学',
 '応用',
 '中国',
 'フランス',
 '現代',
 '心理',
 '生命']

In [70]:
'システム' in 'プログラミング基礎'

False

In [71]:
a = [1,2]
a.index(1)

0

In [85]:
def count_df(courses, vocab):
    df = {}
    for word in vocab:
        count = 0
        for course in courses:
            if word in course:
                count += 1
        index = vocab.index(word)
        df[index] = count
    return df


df = count_df(courses, vocab)
df

{0: 14,
 1: 14,
 2: 9,
 3: 29,
 4: 6,
 5: 0,
 6: 13,
 7: 0,
 8: 15,
 9: 11,
 10: 1,
 11: 1,
 12: 0,
 13: 1,
 14: 6,
 15: 0,
 16: 0,
 17: 3,
 18: 2,
 19: 7,
 20: 3,
 21: 8,
 22: 3,
 23: 3,
 24: 4,
 25: 8,
 26: 1,
 27: 1,
 28: 3,
 29: 11,
 30: 0,
 31: 7,
 32: 0,
 33: 21,
 34: 13,
 35: 0,
 36: 0,
 37: 6,
 38: 1,
 39: 0,
 40: 1,
 41: 2,
 42: 2}

In [73]:
a = [1,2,3]
a = np.array(a)
a = np.zeros(43, dtype=int)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [92]:
def lec_word_matrix(courses, vocab):
    row_length = len(courses)
    columns_length = len(vocab)
    # print(row_length, columns_length)
    # columns_list = np.zeros(columns_length, dtype=int)
    courses_list = np.zeros((row_length,  columns_length), dtype=int)
    # print(columns_list)
    # print(courses_list)
    for i in range(row_length):
        for j in range(columns_length):
            if vocab[j] in courses[i]:
                courses_list[i][j] = 1
    return courses_list
    
    
matrix = lec_word_matrix(courses, vocab)
# len(lec_word_matrix(courses, vocab))
print(matrix)
print(type(matrix))
print(matrix[0])
len(matrix)

[[0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
<class 'numpy.ndarray'>
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0]


129

In [75]:
vocab = 'a'
course = 'aba'
course.count(vocab)

2

In [76]:
def lec_word_matrix(courses, vocab):
    row_length = len(courses)
    columns_length = len(vocab)
    courses_list = np.zeros((row_length,  columns_length), dtype=int)
    for i in range(row_length):
        for j in range(columns_length):
            if vocab[j] in courses[i]:
                counts = courses[i].count(vocab[j])
                # if counts != 1:
                #    print(counts)
                courses_list[i][j] = counts
    return courses_list

matrix2 = lec_word_matrix(courses, vocab)
print(matrix2)
print(type(matrix2))
print(matrix2[0])

[[0]
 [0]
 [3]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
<class 'numpy.ndarray'>
[0]


In [88]:
a = np.array([[1,0,0],[0,1,0],[0,0,1]])
np.add.reduce(a[:,1])
df[0]

14

Q2.4.2で作成した講義-単語行列の各要素(講義 i の単語 j のTFij )にその単語のIDF値を掛 けたTFIDF値を要素とする行列を作成して返す lec_word_tfidf_matrix 関数を完成させ てください。作成した行列は変数 tfidf_matrix で受け取ります。
ここで、講義 i 、単語 j のTFIDF値は以下のように定義されます。 
TFIDF=TF_ij*log(すべての講義数 /単語jのDF)=TF_ij*log(len(courses)/df[j])
log の計算には np.log() を使用してよいです。


In [102]:
def lec_word_tfidf_matrix(courses, vocab, df):
    tf_matrix = lec_word_matrix(courses, vocab)
    row_length = len(tf_matrix)
    columns_length = len(tf_matrix[0])
    print(row_length, columns_length)
    tfidf_matrix = np.zeros((row_length,  columns_length), dtype=float)
    for i in range(row_length):
        for j in range(columns_length):
            idf = np.log(row_length / (df[j] + 1))
            tfidf_matrix[i][j] = idf * tf_matrix[i][j]
    return tfidf_matrix


tfidf_matrix = lec_word_tfidf_matrix(courses, vocab, df)
print(tfidf_matrix)

129 43
[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         2.55722731 ... 0.         0.         0.        ]
 [0.         0.         2.55722731 ... 0.         0.         0.        ]
 ...
 [2.1517622  0.         0.         ... 0.         0.         0.        ]
 [2.1517622  0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [110]:
!pip install collections

ERROR: Could not find a version that satisfies the requirement collections (from versions: none)
ERROR: No matching distribution found for collections


Q2.4.3で作成した講義-単語行列を元に、入力の講義に対してcos類似度に基づいて他のすべ ての講義との類似度を計算し、類似する講義名をキー、その類似度を値とした辞書を返す以 下の find_similar_course 関数を完成させてください。その際、入力の講義および類似 度が0の講義は辞書に含めないようにしてください。cos類似度の計算にはQ1で作成した関数 を使ってもよいです。

In [128]:
from collections import defaultdict

def find_similar_course(target, matrix, courses):
    dic = defaultdict(float)
    index = courses.index(target)
    iteration = len(matrix)
    # print(index)
    # print(courses[index])
    # print(matrix[index])
    for i in range(iteration):
        course = courses[i]
        if i == index:
            continue
        similarity = cos_sim(matrix[index], matrix[i])
        print(course)
        print(len(matrix[i]))
        print(similarity)
        if similarity:
            dic[course] = similarity
    return dic

#dic = find_similar_course('生態統計学', tfidf_matrix, courses)
dic = find_similar_course('特別講義 国際紛争研究(外国語科目)', tfidf_matrix, courses)
dic
#len(dic)

生産システムI
43
0.0
特別講義 Japan in Today's World(外国語科目)
43
0.7838971170851071
生態統計学
43
nan
商法演習
43
0.0
ロシア・旧ソ連法
43
nan
技術倫理
43
nan
健康心理学
43
0.0
機械設計及び製図
43
nan
農作業実習
43
0.0
グローバル生命倫理
43
0.0
国法学
43
nan
国際政治史
43
0.4188250085823585
特別講義 Conflict Prevention and Post-Conflict Politics(外国語科目) 
43
0.7838971170851071
道徳と教育
43
0.0
臨床現象学
43
nan
教育の公共性を考える
43
0.0
専門講義
43
0.21040872390329826
価値と教育III
43
0.0
日本政治思想史
43
0.0
地域経済フィールドワーク実習
43
0.0
医薬品・医療ビジネス
43
nan
英語科教育法III
43
0.0
教育の方法
43
0.0
高度教養特殊演習(こころの総合人間科学演習)
43
0.0
教育課程
43
0.0
教育と社会
43
0.0
高度教養特殊演習(ダイバーシティ社会をつくる技術)
43
0.0
総合日本語 I(2)(L2)
43
0.0
高度教養特殊演習(ひとをつなぐ まちをつくる)
43
0.0
総合日本語 I(1)(L1)
43
0.0
東西文明学II(言語と歴史3)
43
0.0
東西文明学II(言語と歴史1)
43
0.0
複合系計画論
43
nan
超域文化科学高度教養(芸術作品分析法)
43
0.0
中国語学中国文学演習IX
43
0.20260862175591648
スポーツ科学概論
43
0.0
プログラミング基礎
43
0.0
認知脳科学概論
43
0.0
広域システム概論I
43
0.0
学際科学概論
43
0.0
地理・空間基礎論II
43
0.0
地理・空間基礎論I
43
0.0
東西文明学III(国際社会科学2) 
43
0.29646846996866516
科学技術社会論
43
0.0
数理科学概論 
43
0.0
進化理論[高度教養科目] 
43
nan
物質科学概論
43
0.0
広域システム概論II 
43


/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:7: RuntimeWarning: invalid value encountered in double_scalars
  import sys


defaultdict(float,
            {"特別講義 Japan in Today's World(外国語科目)": 0.7838971170851071,
             '生態統計学': nan,
             'ロシア・旧ソ連法': nan,
             '技術倫理': nan,
             '機械設計及び製図': nan,
             '国法学': nan,
             '国際政治史': 0.4188250085823585,
             '特別講義 Conflict Prevention and Post-Conflict Politics(外国語科目) ': 0.7838971170851071,
             '臨床現象学': nan,
             '専門講義': 0.21040872390329826,
             '医薬品・医療ビジネス': nan,
             '複合系計画論': nan,
             '中国語学中国文学演習IX': 0.20260862175591648,
             '東西文明学III(国際社会科学2) ': 0.29646846996866516,
             '進化理論[高度教養科目] ': nan,
             '東西文明学I(思想と批評1) ': nan,
             '東西文明学I(思想と批評3) ': nan,
             '東西文明学I(思想と批評2) ': nan,
             '東西文明学III(国際社会科学1) ': 0.29646846996866516,
             '東西文明学II(思想と批評2) ': nan,
             '東西文明学II(国際社会科学4) ': 0.29646846996866516,
             '東西文明学III(思想と批評1) ': nan,
             '東西文明学III(思想と批評2) ': nan,
             '総合社会科学高度教養(計